apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 651010102653.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:latest
          ports:
            - containerPort: 80