apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: <frontend-image>:<tag>
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5" # Limit the CPU usage to 0.5 cores
              memory: "512Mi" # Limit the memory usage to 512 MiB
            requests:
              cpu: "0.1" # Request 0.1 cores of CPU
              memory: "128Mi" # Request 128 MiB of memory